### ISSUE TITLE
使用 -l pod路径  没能过滤掉pod的第三方库的方法名

### ISSUE THREAD

**Issue by shixiaoda** [kaich/codeobscure#1]
使用 -r 报错
shixiaodadeMac-mini:Shenma_3.6.0 shixiaoda$ codeobscure -r
/Library/Ruby/Gems/2.0.0/gems/codeobscure-0.1.5.1/lib/codeobscure.rb:54:in `obscure': undefined local variable or method `root_dir' for Codeobscure:Module (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/codeobscure-0.1.5.1/bin/codeobscure:3:in `<top (required)>'
	from /usr/local/bin/codeobscure:22:in `load'
	from /usr/local/bin/codeobscure:22:in `<main>'
shixiaodadeMac-mini:Shenma_3.6.0 shixiaoda$

**Comment by shixiaoda** [comment]
qq： 393259282 大神看到了联系我

**Comment by kaich** [comment]
@shixiaoda 你命令调用错了。应该是readme里面所示：
```
codeobscure -o /Users/mac/Downloads/Examples/Messenger.xcodeproj  -l /Users/mac/Downloads/Examples/Pods,/Users/mac/Downloads/Examples/Download
```

-o 指向项目 .xcodeproj 文件
-l 是不需要混淆库的路径

**Comment by kaich** [comment]
已修复！
