### ISSUE TITLE
好多报错呀

### ISSUE THREAD

**Issue by iosKey** [kaich/codeobscure#10]

**Comment by iosKey** [comment]
很多属性都报这个错 Property with 'retain (or strong)' attribute must be of object type 明明是对象啊

**Comment by iosKey** [comment]
本身就是宏的方法和属性 也有报错

**Comment by kaich** [comment]
@iosKey  什么情况下报这个错误啊？ `Property with 'retain (or strong)' attribute must be of object type`。 还有本身是宏的自己过滤一下，方法和属性没事自己用宏干嘛呢，一般都不会这么做吧。工具这东西满足常用情况，你自己进行了特殊处理，codeobscure也提供了功能，自己用过滤一下就可以了。

**Comment by iosKey** [comment]
单例全部都要过滤？

**Comment by iosKey** [comment]
单例里面的方法，普通model的属性都报错

**Comment by kaich** [comment]
@iosKey  贴代码，具体情况。我不知道你怎么写的！我测试的代码也有单例，没问题的！

**Comment by iosKey** [comment]
#pragma mark - 扫描设备
- (void)scanDeviceswithTime:(NSInteger)time
         currentDeviceBlock:(void (^)(UPBLEDevice *cuDevice))currentDeviceBlock
            deviceListBlock:(void (^)(NSArray<UPBLEDevice *> *cuDevices,NSError *error))deviceListBlock{
    [self.deviceObj scanDeviceswithTime:time progressBlock:^(UPBLEDevice * _Nullable upBLEDevice) {
        if (currentDeviceBlock) {
            currentDeviceBlock?currentDeviceBlock(upBLEDevice):nil;
        }
    } completionBlock:^(NSArray<UPBLEDevice *> * _Nullable upBLEDevices, NSError * _Nullable error) {
        if (deviceListBlock) {
            deviceListBlock?deviceListBlock(upBLEDevices,error):nil;
        }
    }];
}

**Comment by iosKey** [comment]
诸如此类 这种很常规的方法都会报错

**Comment by kaich** [comment]
@iosKey 这些你自己看一下吧，我今天刚刚试了一下随便一个github上的开源oc项目，是没问题的，说明满足常用情况！既然是写oc的，这种问题应该很容易找到原因。
