### ISSUE TITLE
项目被锁了

### ISSUE THREAD

**Issue by Sky891028** [kaich/codeobscure#11]
“xxx" is locked for editing and you may not be able to save your changes. Do you want to unlock it?
点unlock无法解决 会一直弹出

**Comment by kaich** [comment]
没有遇到你说的，不会修改你项目的代码的啊，你可以参考测试项目，文档里面有说明！

**Comment by AlwaysYang** [comment]
> 没有遇到你说的，不会修改你项目的代码的啊，你可以参考测试项目，文档里面有说明！

sudo codeobscure ... 执行之后会把project.pbxproj锁住。 好像是改了修改权限。codeObfuscation.h也是无修改权限

**Comment by kaich** [comment]
@AlwaysYang 为什么要加sudo？

**Comment by AlwaysYang** [comment]
> @AlwaysYang 为什么要加sudo？

注意: 由于苹果新版系统有SIP(系统完整性保护)默认是开启的，所以由于安装方式不同，可能在运行命令的时候出现:attempt to write a readonly database (SQLite3::ReadOnlyException)的问题。如果出现这个问题，请在命令行上加上sudo。
