### ISSUE TITLE
最后一步失败

### ISSUE THREAD

**Issue by BaanX** [kaich/codeobscure#14]
你好,我按照wiki要求来操作,所有都成功了,最后运行项目时也成功了,但并没有被混淆,点击某个方法或者类名可以跳转到codeObfuscation.h,但就是混淆失败.还请多多指教

**Comment by kaich** [comment]
理解清楚混淆。并不会修改代码，混淆代码你自己怎么看？ 混淆是编译之后的可执行文件被混淆了，class-dump解出来的是混淆过的！

**Comment by rollin0-0** [comment]
我也出现了同样的情况 我通过class-dump解出来看到没有被混淆过
