### ISSUE TITLE
执行codeobscure -o xcode工程路径 命令 就中断了

### ISSUE THREAD

**Issue by adamsw** [kaich/codeobscure#16]
System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step': attempt to write a readonly database (SQLite3::ReadOnlyException)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `to_a'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `block in execute'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:95:in `prepare'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/filtsymbols.rb:25:in `insertValue'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:45:in `block (2 levels) in capture'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:44:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:44:in `block in capture'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:39:in `scan'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:39:in `capture'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:194:in `block in genFuncList'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:192:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure/funclist.rb:192:in `genFuncList'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/lib/codeobscure.rb:97:in `obscure'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.6.5/bin/codeobscure:4:in `<top (required)>'
	from /usr/local/bin/codeobscure:22:in `load'
	from /usr/local/bin/codeobscure:22:in `<main>'

**Comment by kaich** [comment]
@adamsw 看帮助文档，里面写的很清楚，加sudo。这和你自己的环境有关系

**Comment by XychloveFhy** [comment]
加了sudo  而且已经安装成功了

**Comment by XychloveFhy** [comment]
所有的命令行要加sudo 才可以

**Comment by kaich** [comment]
@XychloveFhy 这种问题你要看你自己的环境，每个人的不一样。
