### ISSUE TITLE
这个怎么用啊，我用之后为什么生成了一个空的.h

### ISSUE THREAD

**Issue by ruiwang321** [kaich/codeobscure#2]
这个怎么用啊，我用之后为什么生成了一个空的.h

**Comment by kaich** [comment]
readme里面应该比较详细了啊。 你把你的使用的命令行贴出来，我看看！

**Comment by kaich** [comment]
一般最简单的就是codeobscure -o XXXX.xcodeproj, 会把所有的都混淆。 framework是不可混淆的。你就加上 -l  [framework 路径] 来避免framework混淆！

**Comment by ruiwang321** [comment]
OK  我再试试
