### ISSUE TITLE
项目的targe的名字被替换了

### ISSUE THREAD

**Issue by tuluigi** [kaich/codeobscure#21]
<img width="263" alt="00001 2x" src="https://user-images.githubusercontent.com/5189595/47689478-0e807380-dc25-11e8-89a5-4e87576be9ed.png">

使用之后，项目的targe被修改成 XXX.xcodeproj

**Comment by kaich** [comment]
好的，会在近期修复！

**Comment by kaich** [comment]
已经修复了 @tuluigi
