### ISSUE TITLE
你的项目已经失效了吗 gem 都安装不了它

### ISSUE THREAD

**Issue by Gintma** [kaich/codeobscure#22]

**Comment by kaich** [comment]
什么错误， 没有失效。我刚刚试了。你自己检查一下自己的环境

**Comment by LiMing11111** [comment]
> 什么错误， 没有失效。我刚刚试了。你自己检查一下自己的环境

ERROR:  Could not find a valid gem 'codeobscure' (>= 0) in any repository

**Comment by Gintma** [comment]
> 什么错误， 没有失效。我刚刚试了。你自己检查一下自己的环境

奥 我的安装源里没有，换了http://rubygems.org/ 找到了
