### ISSUE TITLE
使用后 通过class-dump查看没有效果

### ISSUE THREAD

**Issue by rollin0-0** [kaich/codeobscure#24]
![image](https://user-images.githubusercontent.com/8350316/49988784-0b61fc80-ffb3-11e8-8ff6-d6d3545a15b0.png)

**Comment by rollin0-0** [comment]
生成了 codeObfuscation.h文件 可是class-dump出来发现什么都没有改变 这可能是什么原因呢？Mac OS 10.14.2 Xcode10.1

**Comment by kaich** [comment]
@rowliny 导入生成的 codeObfuscation.h文件 没有啊？

**Comment by kaich** [comment]
@rowliny 我已经上传class_dump之后的效果图了。
