### ISSUE TITLE
作者您好，很高兴看到了您的文章

### ISSUE THREAD

**Issue by Xcode123456** [kaich/codeobscure#28]
可不可自己定义混淆的名字？ 看到了您的那个命令有-t c.这现在可以用了吗？怎么使用

**Comment by kaich** [comment]
这个暂时没有实现呢，貌似平常使用中一般不会遇到这种情况。看大家需求，以后需求多久实现

**Comment by Xcode123456** [comment]
我们这里需要这个东西，想要自己定义它，😂
