### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by iptodays** [kaich/codeobscure#3]
使用时如果主目录为中文，则无法使用

**Comment by kaich** [comment]
@CoderDwang 一般项目路径和文件夹也不建议带有中文。我查查看问题所在。谢谢反馈

**Comment by kaich** [comment]
@CoderDwang 具体什么问题，我在项目主目录和上级目录都添加了中文，都可以正常生成codeObfuscation.h 文件。请问你的问题是怎么操作的？

**Comment by iptodays** [comment]
![snip20180207_363](https://user-images.githubusercontent.com/15830996/35900967-8c59a434-0c0f-11e8-8221-b063ee53ad56.png)

**Comment by kaich** [comment]
你好，主项目全部是中文确实有问题。这是第三方库导致的！目前无法修改，请把它改成英文或者拼音！

**Comment by iptodays** [comment]
ok. ok 谢啦


CoderDwang

在2018年02月7日 15:40，kai cheng<notifications@github.com><mailto:notifications@github.com> 写道：

你好，主项目全部是中文确实有问题。这是第三方库导致的！目前无法修改，请把它改成英文或者拼音！
