### ISSUE TITLE
你好，请问自定义混淆名字什么时候能出版，这里很期待，也很需要。😂

### ISSUE THREAD

**Issue by Xcode123456** [kaich/codeobscure#31]

**Comment by kaich** [comment]
说一下使用场景，如果需要的人多，就实现它

**Comment by whbalzac** [comment]
想混淆后上线？Apple针对混淆后的“乱码名字”能识别，会被拒。

**Comment by Xcode123456** [comment]
我们不是为了马甲包那一类的，只是为了安全，但是苹果有审核关于混淆的，怕被拒，所以不太像把名字混淆的那么乱，想自己定义看起来合理一点的。

**Comment by kaich** [comment]
@whbalzac 用W会替换成单词，我已经把ViewController等重要的关键词都保留了，避免过度混淆！

**Comment by kaich** [comment]
@whbalzac  有多重混淆方式啊，之前有人上线了。而且都保留特征了...

**Comment by HackRoy** [comment]
/Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:3:in `require_relative': cannot load such file -- /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/filtSymbols.rb (LoadError)
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:3:in `<module:FuncList>'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/bin/codeobscure:2:in `<top (required)>'
	from /usr/bin/codeobscure:23:in `load'
	from /usr/bin/codeobscure:23:in `<main>'
