### ISSUE TITLE
你好，我的工程混淆 了之后，用真机跑，一直报我没有操作工程的权限了，为什么？ 但是我在简介里看的还是读和写的权限的啊。

### ISSUE THREAD

**Issue by Xcode123456** [kaich/codeobscure#32]

**Comment by Xcode123456** [comment]
![image](https://user-images.githubusercontent.com/28332571/56569785-42dd5700-65ec-11e9-9838-792a604a17ac.png)
![image](https://user-images.githubusercontent.com/28332571/56569844-5be60800-65ec-11e9-8376-98ad735ce64f.png)

**Comment by kaich** [comment]
@Xcode123456  https://blog.csdn.net/weixin_34293059/article/details/86325675 用这种方法试试
