### ISSUE TITLE
你好，我用的命令是 -f f -t w 为什么 在混淆的时候有的属性名也会被混淆了呢

### ISSUE THREAD

**Issue by Xcode123456** [kaich/codeobscure#34]

**Comment by Xcode123456** [comment]
![image](https://user-images.githubusercontent.com/28332571/56728574-abac0700-6785-11e9-915a-f1ef7ad83fc7.png)

**Comment by Xcode123456** [comment]
你好，我这里重新跑了一下，项目里的类名（类名好像都混了，随机看的）和属性（属性的只是一部分）被混淆了，我使用的命令还是 -f f.正常应该只是混淆方法的。我看了下您的代码，
![image](https://user-images.githubusercontent.com/28332571/56784880-5b848180-6825-11e9-9e58-61bbbe17f69c.png) ，是不是这里没有传递参数从而使用了默认的 f p c了呢。不知道看的对不对，希望您这里有时间看一下。感激不尽

**Comment by kaich** [comment]
没有，您可以拿我文档里面的两个开源项目实例来尝试。用C会只混淆类名

**Comment by jianqingyu** [comment]
为什么我跑了codescure这些命令，没反应的，demo也没反应的，就生成了一个func.list的空文件

**Comment by kaich** [comment]
@jianqingyu 重开一个，不要在别人的issue里面写别人主题无关的issue
