### ISSUE TITLE
方法混淆，不支持多参数字符串

### ISSUE THREAD

**Issue by crazyyuan** [kaich/codeobscure#35]
如：- (instancetype)initWithType:(int)type title:(NSString *)title;
只会混淆initWithType。

**Comment by kaich** [comment]
只是觉得没有必要呢，函数主题第一段代表函数的意义。既然都混淆第一段了。那么后面基本都看不出来是什么了。。

**Comment by Xcode123456** [comment]
为什么 有的方法 被混淆之后会crash啊，能给说一下吗。很好奇也很奇怪。

**Comment by kaich** [comment]
@Xcode123456 看下说明文档，就知道了
