### ISSUE TITLE
动态属性混淆错误

### ISSUE THREAD

**Issue by crazyyuan** [kaich/codeobscure#36]
在碰到以下这种时，是可以用.语法来进行正常的属性操作的，但是混淆了会不匹配，报错。
- (CGFloat)lastKeyboardHeight
- (void)setLastKeyboardHeight:(CGFloat)argv

**Comment by kaich** [comment]
能否贴出具体类的详情，或者只提供方法体和属性

**Comment by kaich** [comment]
@crazyyuan 
混淆如下
    #define lastKeyboardHeight zbvkRweASsObyRtu
    #define _lastKeyboardHeight _zbvkRweASsObyRtu
    #define setLastKeyboardHeight setZbvkRweASsObyRtu

经过测试，你提出来的方法是没有问题的。
