### ISSUE TITLE
混淆宏定义建议加上#ifndef

### ISSUE THREAD

**Issue by crazyyuan** [kaich/codeobscure#37]
避免跟已有宏定义冲突。

**Comment by Xcode123456** [comment]
![image](https://user-images.githubusercontent.com/28332571/56784807-f892ea80-6824-11e9-8dcf-9d22edab29ce.png)
缺少了endif

**Comment by kaich** [comment]
我到时候添加一下，不过加上了之后生成的文件就不是那么便于查看了。到时候作为一个可选项加上吧

**Comment by kaich** [comment]
@crazyyuan 有个疑问，难道自己写的代码，宏定义一般为什么会有和类名和属性名是一样的？

**Comment by crazyyuan** [comment]
> @crazyyuan 有个疑问，难道自己写的代码，宏定义一般为什么会有和类名和属性名是一样的？

随了类，属性，还有字符串的宏定义，为了以防万一。

**Comment by kaich** [comment]
@crazyyuan 好的，已修改
