### ISSUE TITLE
属性正则匹配有问题

### ISSUE THREAD

**Issue by crazyyuan** [kaich/codeobscure#39]
在碰到如下属性时，NSUInteger会被解析出来，而maximumTextLength不解析。
@property(nonatomic, assign) IBInspectable NSUInteger maximumTextLength;

**Comment by kaich** [comment]
嗯嗯，好的，我测试一下，之后修复！

**Comment by crazyyuan** [comment]
另外，带有getter的属性也会有解析问题，isQmui_dataLoaded方法被混淆后报错。
@property(nonatomic, assign, getter = isQmui_dataLoaded) BOOL qmui_dataLoaded;

**Comment by crazyyuan** [comment]
> 另外，带有getter的属性也会有解析问题，isQmui_dataLoaded方法被混淆后报错。
> @Property(nonatomic, assign, getter = isQmui_dataLoaded) BOOL qmui_dataLoaded;

应该是说getter会被混淆，然后报错。

**Comment by kaich** [comment]
这种自己加过滤一下吧，很少代码会这样写，这种情况也不多！

**Comment by kaich** [comment]
@crazyyuan `@Property(nonatomic, assign) IBInspectable NSUInteger maximumTextLength;`这个东西肯定不能混淆啊，混淆了，加载xib不就崩了
