### ISSUE TITLE
codeobscure -o 没反应

### ISSUE THREAD

**Issue by jianqingyu** [kaich/codeobscure#40]
Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:194:in `read': No such file or directory @ rb_sysopen - //Users/iosdevop/Downloads/ToThePenny-master/Pods/Headers/Public/KVNProgress/UIImage+KVNEmpty.h (Errno::ENOENT),产生这些错误为什么我跑了codescure这些命令，没反应的，演示也没反应的，就生成了一个func.list的空文件

**Comment by kaich** [comment]
看下例子和文档啊，要过滤pods里面的文件

**Comment by jianqingyu** [comment]
你好，我执行gem install codeobscure提示没权限 然后就sudo gem install /usr/local/bin codeobscure 后面就提示Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:194:in `read': No such file or directory @ rb_sysopen - //Users/iosdevop/Downloads/ToThePenny-,是不是没安装成功。因为例子也没成功

**Comment by jianqingyu** [comment]
我pod里面没没文件

**Comment by kaich** [comment]
//Users/iosdevop/Downloads/ToThePenny-master/Pods/Headers/Public/KVNProgress/UIImage+KVNEmpty.h  你这个不是pods里面的么？

**Comment by kaich** [comment]
@jianqingyu  类似这种`codeobscure -o /Users/mk/Downloads/ToThePenny-master\ 2/Depoza.xcodeproj -l /Users/mk/Downloads/ToThePenny-master\ 2/Pods ` 这个命令啊。 文档里面讲的很清楚

**Comment by jianqingyu** [comment]
您好，我的意思是新建的一个项目没有pod的也没反应

**Comment by jianqingyu** [comment]
您演示的gem install codeobscure以后  直接codeobscure -o接绝对路径工程.xcodeproj就可以混淆。我这边同样操作没反应，xcode10.2

**Comment by kaich** [comment]
晕了，你问新建工程的问题，贴Demo工程的错误干嘛。你要把问题描述清楚啊，不同问题放在不同issue里面

**Comment by jianqingyu** [comment]
我的问题就是为什么gem install codeobscure以后直接codeobscure -o接绝对路径工程.xcodeproj这2步没有反应

**Comment by kaich** [comment]
没有反应总会出来点错误什么的吧

**Comment by jianqingyu** [comment]
nihao  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step': attempt to write a readonly database (SQLite3::ReadOnlyException)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `to_a'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `block in execute'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:95:in `prepare'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/filtsymbols.rb:25:in `insertValue'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:46:in `block (2 levels) in capture'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:45:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:45:in `block in capture'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:40:in `scan'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:40:in `capture'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:195:in `block in genFuncList'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:193:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:193:in `genFuncList'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure.rb:107:in `obscure'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/bin/codeobscure:4:in `<top (required)>'
	from /usr/local/bin/codeobscure:23:in `load'
	from /usr/local/bin/codeobscure:23:in `<main>'

**Comment by kaich** [comment]
>>> 注意: 由于苹果新版系统有SIP(系统完整性保护)默认是开启的，所以由于安装方式不同，可能在运行命令的时候出现:attempt to write a readonly database (SQLite3::ReadOnlyException)的问题。如果出现这个问题，请在命令行上加上sudo。

文档上写的很清楚

**Comment by jianqingyu** [comment]
非常感谢，成功了，混淆了文件类名

**Comment by jianqingyu** [comment]
但是方法名跟属性没反应

**Comment by kaich** [comment]
先看文档
