### ISSUE TITLE
麻烦帮我看下这是什么错误啊

### ISSUE THREAD

**Issue by SKCodeing** [kaich/codeobscure#41]
/Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:3:in `require_relative': cannot load such file -- /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/filtSymbols.rb (LoadError)
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:3:in `<module:FuncList>'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/bin/codeobscure:2:in `<top (required)>'
	from /usr/bin/codeobscure:23:in `load'
	from /usr/bin/codeobscure:23:in `<main>'

**Comment by kaich** [comment]
尊重下啊。连提个问题都不愿意花时间写清楚。遇到错误的。基本的输入、输出提问规则都不写。

**Comment by SKCodeing** [comment]
您好 实在不好意思，现在附上输入输出
Last login: Fri May 31 17:35:44 on ttys007
localhost:~ Hack$ codeobscure -o /Users/Hack/Desktop/小红书\ iOS客户端/小红书/小红书.xcodeproj  -l /Users/Hack/Desktop/小红书\ iOS客户端/小红书/Pods 
/Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:3:in `require_relative': cannot load such file -- /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/filtSymbols.rb (LoadError)
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:3:in `<module:FuncList>'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure/funclist.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/lib/codeobscure.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.7.5/bin/codeobscure:2:in `<top (required)>'
	from /usr/bin/codeobscure:23:in `load'
	from /usr/bin/codeobscure:23:in `<main>'
localhost:~ Hack$

**Comment by SKCodeing** [comment]
其实输入和输出我就是照着您的教程写的，是不是 我的开发环境有问题呢？Mac 10.14.5系统版本
ruby 2.3.7p456 版本

**Comment by kaich** [comment]
先试一下文档提供的Demo，看能不能跑的通。
1.  先试一下命令行之前加sudo。
2. 尝试升级一下ruby版本试试。 我的是2.5

**Comment by SKCodeing** [comment]
Traceback (most recent call last):
	4: from /Users/Hack/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
	3: from /Users/Hack/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
	2: from /Users/Hack/.rvm/gems/ruby-2.5.5/bin/codeobscure:23:in `<main>'
	1: from /Users/Hack/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems.rb:302:in `activate_bin_path'
/Users/Hack/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem codeobscure (>= 0.a) with executable codeobscure (Gem::GemNotFoundException)
localhost:~ Hack$ gem -v


尝试了都不行，麻烦问下您的gem 版本多少？我的3.0.3

**Comment by kaich** [comment]
Demo 试了的没有

**Comment by kaich** [comment]
@HackRoy 应该是你路径的问题，尽量不要带中文和空格
