### ISSUE TITLE
执行codeobscure命令过程中，最后打印如下信息就结束了，没有生成混淆文件，请问怎么处理？

### ISSUE THREAD

**Issue by jackieyiprylink** [kaich/codeobscure#43]
```
/Library/Ruby/Gems/2.3.0/gems/random-word-2.1.1/lib/random_word.rb:61:in `excluded?': undefined method `length' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/random-word-2.1.1/lib/random_word.rb:23:in `block in each_randomly'
	from /Library/Ruby/Gems/2.3.0/gems/random-word-2.1.1/lib/random_word.rb:19:in `loop'
	from /Library/Ruby/Gems/2.3.0/gems/random-word-2.1.1/lib/random_word.rb:19:in `each_randomly'
	from /usr/bin/codeobscure:1:in `each'
```
备注：
1、如上错误，是使用随机单词混淆(-t w)执行命令codeobscure出现的，而使用随机字符混淆没问题。（像是random_word的问题）
2、自己写的简单Demo，用随机单词和随机字符都没问题。但是在已上线比较大的项目里使用随机单词混淆会出现如上问题。

本机环境：
RUBYGEMS VERSION: 2.7.7
RUBY VERSION: 2.3.7 (2018-03-28 patchlevel 456) [universal.x86_64-darwin18]
INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.3.0

**Comment by kaich** [comment]
你们项目到底有多大啊，可能是随机单词全给用完了。有些通用库该过滤就过滤。 另外把教程看一遍，混淆文件要加到功能里面的

**Comment by jackieyiprylink** [comment]
> 你们项目到底有多大啊，可能是随机单词全给用完了。有些通用库该过滤就过滤。 另外把教程看一遍，混淆文件要加到功能里面的

感谢大佬！随机单词混淆跑通了
