### ISSUE TITLE
工程较大,使用混淆后只混淆了一小部分

### ISSUE THREAD

**Issue by ATMLGG** [kaich/codeobscure#44]
使用-t w -s后,一个类中只混淆了几个属性和方法,但是混淆的头文件codeObfuscation.h中一共有2977行,是否是词库用完了导致混淆代码较少呢

**Comment by kaich** [comment]
不报错，说明词库没问题。

**Comment by ATMLGG** [comment]
那是否有默认混淆百分比呢,如果有,能否修改

**Comment by kaich** [comment]
没有的，检查自己配置是否有问题。
