### ISSUE TITLE
通过class-dump查看没有效果

### ISSUE THREAD

**Issue by ZengFan-yu** [kaich/codeobscure#45]
我是根据教程来的，codeObfuscation.h也生成了。但是archive里的.app导出后的.h没有效果，求问是什么原因？
<img width="765" alt="image" src="https://user-images.githubusercontent.com/39817482/69844963-7d595180-12a9-11ea-922a-57ea85032b8d.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/39817482/69845017-d32df980-12a9-11ea-8111-ea14b4402a02.png">

**Comment by kaich** [comment]
@ZengFan-yu 检查自己的配置，都文件是否导入，如果没有看文档，先把文档看一遍
