### ISSUE TITLE
请教，系统升级到10.13.4 (17E199)后报错

### ISSUE THREAD

**Issue by ghost** [kaich/codeobscure#5]
`/Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.5.3/lib/codeobscure.rb:80:in `block in obscure': undefined local variable or method `path' for Codeobscure:Module (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.5.3/lib/codeobscure.rb:75:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.5.3/lib/codeobscure.rb:75:in `obscure'
	from /Library/Ruby/Gems/2.3.0/gems/codeobscure-0.1.5.3/bin/codeobscure:3:in `<top (required)>'
	from /usr/local/bin/codeobscure:22:in `load'
	from /usr/local/bin/codeobscure:22:in `<main>'`

**Comment by kaich** [comment]
@yazi-xiaofan  请问codeobscure的版本是多少？ 是之前可以，升级系统之后就不行了吗？

**Comment by kaich** [comment]
你好，确实有问题，在路径不对的时候会有问题，已经修复了！更新一下，版本1.5.8  @yazi-xiaofan

**Comment by ghost** [comment]
好的，谢谢
