### ISSUE TITLE
请不要混淆 IBAction 和 IBOutlet

### ISSUE THREAD

**Issue by KyonLi** [kaich/codeobscure#6]
在使用ib的项目里混淆了`IBOutlet`声明的变量和`IBAction `声明的方法会导致非常多的问题

**Comment by kaich** [comment]
@KyonLi 可以先使用codeobscure吧IBOutlet 和 IBAction 给过滤掉！ 你试一下！具体在说明里面有！如下： 

> 在0.1.3中，你并不要简单的删掉它，而是先运行codeobscure -i XcodeprojPath去生成ignoresymbols。然后把需要进一步过滤的某些名字直接添加进入，用英文逗号分隔开来。例如上面你要删除的，如果你仅仅是删除了，下次要执行codeobscure -o重新生成的时候会又重新生成，你要再次把它从codeObfuscation.h中查询出来并删除。v0.1.3中你仅仅添加到ignoresymbols就可以很方便的解决这一问题。下次codeobscure -o生成的时候回自动过滤到这些字段。

**Comment by KyonLi** [comment]
@kaich 已经尝试过在 ignoresymbols 文件中加入 IBAction 和 IBOutlet，无效。如果您说的是加入IBAction所对应的方法名那么是有效的，可是工作量过于巨大了

**Comment by kaich** [comment]
@KyonLi 好的，我试试看

**Comment by kaich** [comment]
@KyonLi  你把具体问题说一下，我随便创建个工程，加上IBAction 和 IBOutlet， 经过混淆是可以的啊！ 你错误具体是什么？

**Comment by KyonLi** [comment]
```bash
iMac:Desktop kyon$ codeobscure -i /Users/kyon/Desktop/sample/sample.xcodeproj
iMac:Desktop kyon$ codeobscure -o /Users/kyon/Desktop/sample/sample.xcodeproj -t w -f p,f
"p:[window]"
"f:[application]"
"f:[didFinishLaunchingWithOptions]"
"f:[applicationWillResignActive]"
"f:[applicationDidEnterBackground]"
"f:[applicationWillEnterForeground]"
"f:[applicationDidBecomeActive]"
"f:[applicationWillTerminate]"
"f:[application]"
"f:[applicationWillResignActive]"
"f:[applicationDidEnterBackground]"
"f:[applicationWillEnterForeground]"
"f:[applicationDidBecomeActive]"
"f:[applicationWillTerminate]"
"f:[button1Clicked]"
"f:[button2Clicked]"
"f:[viewDidLoad]"
"f:[didReceiveMemoryWarning]"
"f:[button1Clicked]"
"f:[button2Clicked]"
"p:[UIButton]"
"p:[UIButton]"
/Library/Ruby/Gems/2.3.0/gems/random-word-2.1.0/lib/random_word.rb:90: warning: Enumerator.new without a block is deprecated; use Object#to_enum
配置完成!
请直接运行项目，如果项目中出现类似: `+[LoremIpsum PyTJvHwWNmeaaVzp:]: unrecognized selector sent to class`。在codeObfuscation.h中查询PyTJvHwWNmeaaVzp并删除它!
iMac:Desktop kyon$ 
iMac:Desktop kyon$ gem list --local codeobscure

*** LOCAL GEMS ***

codeobscure (0.1.5.8)
```

[sample.zip](https://github.com/kaich/codeobscure/files/2015751/sample.zip)

**Comment by KyonLi** [comment]
IBOutlet 过滤掉了，之前出问题应该是恰好和别的类里的重名了，可是 IBAction 没有过滤掉。
由于宏不适用于 ib，点击按钮就会崩溃
`2018-05-18 14:55:30.797433+0800 sample.xcodeproj[8058:17623226] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ViewController button1Clicked:]: unrecognized selector sent to instance 0x7fbdca510be0'`

**Comment by kaich** [comment]
@KyonLi 知道问题了，正在修复！

**Comment by kaich** [comment]
@KyonLi  修复了更新一下 版本 0.1.5.9

**Comment by KyonLi** [comment]
新版没问题了，赞美作者！
