### ISSUE TITLE
object c. unity 

### ISSUE THREAD

**Issue by levine2008** [kaich/codeobscure#7]
unity5.3 生成的xcode 工程，oc 代码进行混淆，有问题，麻烦看一下

**Comment by kaich** [comment]
@levine2008 具体什么问题？ 你发到这里，我看一下！

**Comment by wakeupyq** [comment]
作者能不能考虑提供不混淆属性的方法，因为字典转模型用到了第三方库（MJExtension），这时属性如果混淆了就可能导致解析不成功。

**Comment by kaich** [comment]
@wakeupyq  看一下这个参数：`-f, --fetch type1,type2,type3    fetch and replace type,default type is [c,p,f].c for class,p for property,f for function`。 你自己看一下。 c 是class。 p是属性，f 是方法！可以结合这个参数选择你要混淆的

**Comment by wakeupyq** [comment]
为什么使用-l参数无效？

**Comment by wakeupyq** [comment]
为什么设置-l参数无效？我是这样设置的：codeobscure -o /Users/yangqin/Desktop/TestDemo/TestDemo.xcodeproj -i /Users/yangqin/Desktop/TestDemo/Pods
但是pods下的所有三方库的属性和函数仍然被编译进去了

**Comment by kaich** [comment]
@wakeupyq  是-l 不是 -i

**Comment by kaich** [comment]
@wakeupyq 我加了一些实例，在项目主页。你可以看下！

**Comment by wakeupyq** [comment]
@kaich 不好意思，刚刚代码赋值粘贴错了，我是使用的如下命令
codeobscure -o /Users/yangqin/Desktop/TestDemo/TestDemo.xcodeproj -l /Users/yangqin/Desktop/TestDemo/Pods
![image](https://user-images.githubusercontent.com/8341067/40907248-cc4b8a0a-6815-11e8-9191-9a72463c8d92.png)

**Comment by kaich** [comment]
@wakeupyq 已经修复， 正在提交0.1.6版本，一会 `gem update codeobscure`更新到0.1.6就可以了。

**Comment by wakeupyq** [comment]
@kaich 好的

**Comment by kaich** [comment]
没有提供具体问题描述也无回应，关闭问题
