### ISSUE TITLE
关于使用-l参数忽略某些文件的问题

### ISSUE THREAD

**Issue by wakeupyq** [kaich/codeobscure#8]
我使用了最新版本0.1.6.1,设置被忽略的文件价里的方法名和属性名能够不被混淆，类名仍然被混淆了，麻烦作者再看看呢。

**Comment by kaich** [comment]
@wakeupyq 把具体情况列出来，提出个问题，什么都不列出来是无法校验修正的。输入 输出 结果！

**Comment by wakeupyq** [comment]
@kaich 
**我的工程目录如下**
<img width="816" alt="image" src="https://user-images.githubusercontent.com/8341067/41081125-2fd3eb4c-6a5c-11e8-85d0-d74b40ca6ffa.png">
**使用的命令**
`codeobscure -o /Users/mac/Desktop/TestDemo/TestDemo.xcodeproj -l /Users/mac/Desktop/TestDemo/Pods,/Users/mac/Desktop/TestDemo/TestDemo/Vendor -t w`
**生成的映射头文件为**
![image](https://user-images.githubusercontent.com/8341067/41081227-a1465170-6a5c-11e8-8fe5-3cf8af7bb1b5.png)
 **如上描述，iflyMSC这个三方库是存在我所设置的忽略文件夹Vendor 下的，iflyMSC相关属性和方法可以按照我预想的不被混淆，但是相关的类名却被被混淆了。**

**Comment by kaich** [comment]
@wakeupyq  已经定位到问题，已经修复了。`gem update codeobscure` 更新一下。最新版本0.1.6.2!
非常感谢反馈，这个问题应该很早就有了！如果确认修复了，就关掉issue

**Comment by wakeupyq** [comment]
@kaich 好的，目前没发现问题了，谢谢作者提供这么好的工具
