### ISSUE TITLE
提示成功之后 无任何混淆信息

### ISSUE THREAD

**Issue by iptodays** [kaich/codeobscure#9]
如题

**Comment by kaich** [comment]
@CoderDwang 我测试是可以的。你不可以详细说明 输入、输出、结果。 这么简单的几个字，我是没办法定位问题的！

**Comment by kaich** [comment]
@CoderDwang 没法确定是不是你自己用的问题！

**Comment by iptodays** [comment]
好像是我这边的原因。试了一下 又可以了。
